//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetChess.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_NETCHETYPE                  129
#define IDD_DIALOG_OPTIONS              131
#define IDB_BITMAP_BASE                 132
#define IDB_BITMAP_ROOK_WHITE           133
#define IDB_BITMAP_BISHOP_WHITE         134
#define IDB_BITMAP_KING_BLACK           135
#define IDB_BITMAP_KING_WHITE           136
#define IDB_BITMAP_KNIGHT_BLACK         137
#define IDB_BITMAP_KNIGHT_WHITE         138
#define IDB_BITMAP_PAWN_BLACK           139
#define IDB_BITMAP_PAWN_WHITE           140
#define IDB_BITMAP_QUEEN_BLACK          141
#define IDB_BITMAP_QUEEN_WHITE          142
#define IDB_BITMAP_ROOK_BLACK           143
#define IDB_BITMAP_BISHOP_BLACK         144
#define IDD_DIALOG_SERVER_INFO          145
#define IDD_DIALOG_MESSAGE              146
#define IDD_DIALOG_HISTORY              147
#define IDD_DIALOG_PICK_PIECE           148
#define IDI_ICON_MAINFRAME_OPPOSITE     149
#define IDR_SHELL_MENU                  150
#define IDD_DIALOG_PROPERTIES           177
#define IDD_DIALOG_ACCEPT               178
#define IDD_DIALOG_LOST_PIECE           179
#define IDD_DIALOG_DEMO_FEED            180
#define IDB_BITMAP_DICE                 186
#define IDB_BITMAP_DICE1                187
#define IDB_BITMAP_DICE2                188
#define IDB_BITMAP_DICE3                189
#define IDB_BITMAP_DICE4                190
#define IDB_BITMAP_DICE5                191
#define IDB_BITMAP_DICE6                192
#define IDD_DIALOG_GAMETYPE             197
#define IDB_BITMAP1_ORG                 198
#define IDB_BITMAP_ORG                  202
#define IDC_CHECK_WHITE_ON_TOP          1000
#define IDC_BUTTON_WHITE_COLOR          1001
#define IDC_BUTTON_BLACK_COLOR          1002
#define IDC_STATIC_WHITE                1003
#define IDC_STATIC_BLACK                1004
#define IDC_EDIT_PORT_NUMBER            1007
#define IDC_IPADDRESS                   1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_RECEIVE_MESSAGE        1010
#define IDC_EDIT_HISTORY                1011
#define IDC_STATIC_ROOT_WHITE           1013
#define IDC_STATIC_BITMAP_KNIGHT        1014
#define IDC_STATIC_BISHOP_WHITE         1015
#define IDC_STATIC_QUEEN_WHITE          1016
#define IDC_STATIC_KING_WHITE           1017
#define IDC_STATIC_PAWN_WHITE           1018
#define IDC_STATIC_ROOT_BLACK           1019
#define IDC_STATIC_KNIGHT_BLACK         1020
#define IDC_STATIC_BISHOP_BLACK         1021
#define IDC_STATIC_QUEEN_BLACK          1022
#define IDC_STATIC_KING_BLACK           1023
#define IDC_STATIC_PAWN_BLACK           1024
#define IDC_STATIC_STATUS               1025
#define IDC_STATIC_IP_ADDRESS           1026
#define IDC_STATIC_CLIENT_STATUS        1026
#define IDC_STATIC_EMPTY                1027
#define IDC_STATIC_PIECE_TYPE1          1028
#define IDC_STATIC_PIECE_TYPE2          1029
#define IDC_STATIC_PIECE_TYPE3          1030
#define IDC_RADIO_WHITE                 1032
#define IDC_RADIO_BLACK                 1033
#define IDC_STATIC_ACCEPT               1037
#define IDC_STATIC_W1                   1038
#define IDC_STATIC_W2                   1039
#define IDC_STATIC_W3                   1040
#define IDC_STATIC_W4                   1041
#define IDC_STATIC_W5                   1042
#define IDC_STATIC_W6                   1043
#define IDC_STATIC_W7                   1044
#define IDC_STATIC_W8                   1045
#define IDC_STATIC_W9                   1046
#define IDC_STATIC_W10                  1047
#define IDC_STATIC_W11                  1048
#define IDC_STATIC_W12                  1049
#define IDC_STATIC_W13                  1050
#define IDC_STATIC_W14                  1051
#define IDC_STATIC_W15                  1052
#define IDC_STATIC_W16                  1053
#define IDC_STATIC_B1                   1054
#define IDC_STATIC_B2                   1055
#define IDC_STATIC_B3                   1056
#define IDC_STATIC_B4                   1057
#define IDC_STATIC_B5                   1058
#define IDC_STATIC_B6                   1059
#define IDC_STATIC_B7                   1060
#define IDC_STATIC_B8                   1061
#define IDC_STATIC_B9                   1062
#define IDC_STATIC_B10                  1063
#define IDC_STATIC_B11                  1064
#define IDC_STATIC_B12                  1065
#define IDC_STATIC_B13                  1066
#define IDC_STATIC_B14                  1067
#define IDC_STATIC_B15                  1068
#define IDC_STATIC_B16                  1069
#define IDC_COMBO_FROM_LETTER           1076
#define IDC_COMBO_FROM_NUMBER           1077
#define IDC_COMBO_TO_LETTER             1078
#define IDC_COMBO_TO_NUMBER             1079
#define IDC_BUTTON_ADD                  1083
#define IDC_RADIO_TOSS                  1084
#define IDC_RADIO_HC                    1087
#define IDC_BUTTON_LAST                 1088
#define IDC_RADIO_HH                    1088
#define IDC_RADIO_SINGLE                1089
#define IDC_EDIT_PLAYER1NAME            1090
#define IDC_EDIT_PLAYER2NAME            1091
#define IDC_RADIO_COMPUTER              1092
#define IDC_RADIO_HHM                   1093
#define ID_VIEW_HIDE                    32771
#define ID_EDIT_OPTIONS                 32772
#define ID_TOOLS_CLIENT                 32773
#define ID_TOOLS_SERVER                 32774
#define ID_TOOLS_SENDMESSAGE            32775
#define ID_TOOLS_HISTORY                32778
#define ID_VIEW_NUMBER                  32779
#define ID_VIEW_LETTER                  32780
#define ID_FILE_SAVEHISTORY             32781
#define ID_TOOLS_PLAYHISTORY            32782
#define ID_SHELL_CLOSE                  32783
#define ID_SHELL_VIEW                   32784
#define ID_VIEW_HISTORY                 32786
#define ID_TOOLS_WHITEONTOP             32787
#define ID_EDIT_MOVEFIRST               32792
#define ID_EDIT_MOVELAST                32793
#define ID_HELP_HOWTOPLAY               32799
#define ID_TOOLS_DISCONNECT             32800
#define ID_EDIT_PROPERTIES              32801
#define D_EDIT_PROPERTIES               32802
#define ID_TOOLS_RESIGN                 32804
#define ID_TOOLS_DRAW                   32805
#define ID_VIEW_LOSTPIECES              32806
#define ID_FILE_FEED                    32807
#define ID_TOOLS_LEARN                  32808
#define ID_EDIT_SETBOARD                32809
#define ID_EDIT_GAMETYPE                32810
#define ID_EDIT_PLAYER1COLOR            32811
#define ID_EDIT_PLAYER2COLOR            32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
